repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Run cargo fmt
        entry: cargo fmt --all -- --check --color always
        language: system
        pass_filenames: false

      - id: cargo-clippy
        name: Run cargo clippy
        entry: cargo clippy --all-targets -- -D warnings
        language: system
        pass_filenames: false
